# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        /post/:title

# Setup
title:            "Tyler Benziger"
description:      "Tyler Benziger writes about things"
url:              http://tybenz.com
baseurl:          "/"
paginate:         5

author:
  name:           "Tyler Benziger"

# Custom vars
twitter:        https://twitter.com/tybenz
github:         https://github.com/tybenz
