# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        /post/:title

# Setup
title:            "Tyler Benziger"
description:      "Tyler Benziger writes about things"
url:              http://tybenz.github.io
baseurl:          "/"

author:
  name:           "Tyler Benziger"

# Custom vars
twitter:        https://twitter.com/tybenz
github:         https://github.com/tybenz
